apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  labels:
    run: mongo-sts-demo
spec:
  ports:
  - port: 27017
    name: db
  clusterIP: None
  selector:
    run: mongo-sts-demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sts
spec:
  serviceName: "mongo-headless"
  replicas: 2
  #podManagementPolicy: Parallel
  selector:
    matchLabels:
      run: mongo-sts-demo
  template:
    metadata:
      labels:
        run: mongo-sts-demo
    spec:
      containers:
      - name: mongo
        image: mongo:3.6
        env:
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-db-name
        volumeMounts:
        - name: pv-volume
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: pv-volume
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
