apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  labels:
    run: mongo-sts-demo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: db
  clusterIP: None
  selector:
    run: mongo-sts-demo
